In [1]:
import pandas as pd

In [2]:
data =pd.read_excel("2017 Order Data.xlsx")

In [3]:
data

,Order ID,Customer ID,Cookies Shipped,Revenue,Cost,Order Date,Ship Date,Order Status,Order Adress
0,413383,152689 - YT Restaurants,936,4680.0,2340,2017-12-31,2018-01-05,Shipped,"136 Church St, New York City, NY 10001"
1,751142,985245 - Quick Bite Convenience Stores,987,4935.0,2467.5,2017-12-31,2018-01-04,Shipped,"562 2nd St, New York City, NY 10001"
2,876056,985245 - Quick Bite Convenience Stores,270,1350.0,675,2017-12-30,2018-01-03,Shipped,"277 Main St, New York City, NY 10001"
3,548247,985245 - Quick Bite Convenience Stores,925,4625.0,2312.5,2017-12-30,2018-01-03,Shipped,"410 6th St, San Francisco, CA 94016"
4,626350,152689 - YT Restaurants,974,4870.0,2435,2017-12-29,2018-01-03,Shipped,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...,...,...,...
817,800525,785432 - Park & Eat LLC,164,820.0,410,2017-01-03,2017-01-07,Shipped,"988 Spruce St, Boston, MA 02215"
818,311436,985245 - Quick Bite Convenience Stores,107,535.0,267.5,2017-01-01,2017-01-05,Shipped,"969 11th St, Boston, MA 02215"
819,XXXXXX,XXXXXX - Promo,904,4520.0,2260,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
820,617865,452584 - Acme Grocery Stores,62,310.0,155,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
821,154036,325698 - Cascade Grovers,765,3825.0,1912.5,2017-01-01,2017-01-03,Shipped,"181 12th St, Austin, TX 73301"

In [4]:
data["Customer ID"]

0                     152689 - YT Restaurants
1      985245 - Quick Bite Convenience Stores
2      985245 - Quick Bite Convenience Stores
3      985245 - Quick Bite Convenience Stores
4                     152689 - YT Restaurants
                        ...
817                   785432 - Park & Eat LLC
818    985245 - Quick Bite Convenience Stores
819                            XXXXXX - Promo
820              452584 - Acme Grocery Stores
821                  325698 - Cascade Grovers
Name: Customer ID, Length: 822, dtype: object

In [5]:
#insert a new column "RESTUARANT NAME" at position 2
#insert takes 3 arguments (the position,the column name,the value)
data.insert(2,"Restuarant Name","")

In [6]:
data

,Order ID,Customer ID,Restuarant Name,Cookies Shipped,Revenue,Cost,Order Date,Ship Date,Order Status,Order Adress
0,413383,152689 - YT Restaurants,,936,4680.0,2340,2017-12-31,2018-01-05,Shipped,"136 Church St, New York City, NY 10001"
1,751142,985245 - Quick Bite Convenience Stores,,987,4935.0,2467.5,2017-12-31,2018-01-04,Shipped,"562 2nd St, New York City, NY 10001"
2,876056,985245 - Quick Bite Convenience Stores,,270,1350.0,675,2017-12-30,2018-01-03,Shipped,"277 Main St, New York City, NY 10001"
3,548247,985245 - Quick Bite Convenience Stores,,925,4625.0,2312.5,2017-12-30,2018-01-03,Shipped,"410 6th St, San Francisco, CA 94016"
4,626350,152689 - YT Restaurants,,974,4870.0,2435,2017-12-29,2018-01-03,Shipped,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...,...,...,...,...
817,800525,785432 - Park & Eat LLC,,164,820.0,410,2017-01-03,2017-01-07,Shipped,"988 Spruce St, Boston, MA 02215"
818,311436,985245 - Quick Bite Convenience Stores,,107,535.0,267.5,2017-01-01,2017-01-05,Shipped,"969 11th St, Boston, MA 02215"
819,XXXXXX,XXXXXX - Promo,,904,4520.0,2260,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
820,617865,452584 - Acme Grocery Stores,,62,310.0,155,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
821,154036,325698 - Cascade Grovers,,765,3825.0,1912.5,2017-01-01,2017-01-03,Shipped,"181 12th St, Austin, TX 73301"

In [7]:
data["Customer ID"].str.split("-",expand=True)

           0                               1
0    152689                   YT Restaurants
1    985245    Quick Bite Convenience Stores
2    985245    Quick Bite Convenience Stores
3    985245    Quick Bite Convenience Stores
4    152689                   YT Restaurants
..       ...                             ...
817  785432                   Park & Eat LLC
818  985245    Quick Bite Convenience Stores
819  XXXXXX                            Promo
820  452584              Acme Grocery Stores
821  325698                  Cascade Grovers

[822 rows x 2 columns]

In [8]:
data[["Customer ID","Restuarant Name"]] =data["Customer ID"].str.split("-",expand=True)

In [9]:
data

,Order ID,Customer ID,Restuarant Name,Cookies Shipped,Revenue,Cost,Order Date,Ship Date,Order Status,Order Adress
0,413383,152689,YT Restaurants,936,4680.0,2340,2017-12-31,2018-01-05,Shipped,"136 Church St, New York City, NY 10001"
1,751142,985245,Quick Bite Convenience Stores,987,4935.0,2467.5,2017-12-31,2018-01-04,Shipped,"562 2nd St, New York City, NY 10001"
2,876056,985245,Quick Bite Convenience Stores,270,1350.0,675,2017-12-30,2018-01-03,Shipped,"277 Main St, New York City, NY 10001"
3,548247,985245,Quick Bite Convenience Stores,925,4625.0,2312.5,2017-12-30,2018-01-03,Shipped,"410 6th St, San Francisco, CA 94016"
4,626350,152689,YT Restaurants,974,4870.0,2435,2017-12-29,2018-01-03,Shipped,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...,...,...,...,...
817,800525,785432,Park & Eat LLC,164,820.0,410,2017-01-03,2017-01-07,Shipped,"988 Spruce St, Boston, MA 02215"
818,311436,985245,Quick Bite Convenience Stores,107,535.0,267.5,2017-01-01,2017-01-05,Shipped,"969 11th St, Boston, MA 02215"
819,XXXXXX,XXXXXX,Promo,904,4520.0,2260,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
820,617865,452584,Acme Grocery Stores,62,310.0,155,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
821,154036,325698,Cascade Grovers,765,3825.0,1912.5,2017-01-01,2017-01-03,Shipped,"181 12th St, Austin, TX 73301"

In [10]:
#insert a new column "PROFIT" at position 6
data.insert(6,"profit","")

In [11]:
data

,Order ID,Customer ID,Restuarant Name,Cookies Shipped,Revenue,Cost,profit,Order Date,Ship Date,Order Status,Order Adress
0,413383,152689,YT Restaurants,936,4680.0,2340,,2017-12-31,2018-01-05,Shipped,"136 Church St, New York City, NY 10001"
1,751142,985245,Quick Bite Convenience Stores,987,4935.0,2467.5,,2017-12-31,2018-01-04,Shipped,"562 2nd St, New York City, NY 10001"
2,876056,985245,Quick Bite Convenience Stores,270,1350.0,675,,2017-12-30,2018-01-03,Shipped,"277 Main St, New York City, NY 10001"
3,548247,985245,Quick Bite Convenience Stores,925,4625.0,2312.5,,2017-12-30,2018-01-03,Shipped,"410 6th St, San Francisco, CA 94016"
4,626350,152689,YT Restaurants,974,4870.0,2435,,2017-12-29,2018-01-03,Shipped,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...,...,...,...,...,...
817,800525,785432,Park & Eat LLC,164,820.0,410,,2017-01-03,2017-01-07,Shipped,"988 Spruce St, Boston, MA 02215"
818,311436,985245,Quick Bite Convenience Stores,107,535.0,267.5,,2017-01-01,2017-01-05,Shipped,"969 11th St, Boston, MA 02215"
819,XXXXXX,XXXXXX,Promo,904,4520.0,2260,,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
820,617865,452584,Acme Grocery Stores,62,310.0,155,,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
821,154036,325698,Cascade Grovers,765,3825.0,1912.5,,2017-01-01,2017-01-03,Shipped,"181 12th St, Austin, TX 73301"

In [12]:
data.dtypes

Order ID                   object
Customer ID                object
Restuarant Name            object
Cookies Shipped            object
Revenue                   float64
Cost                       object
profit                     object
Order Date         datetime64[ns]
Ship Date          datetime64[ns]
Order Status               object
Order Adress               object
dtype: object

In [13]:
#checking the distinct value in the cost column
data["Cost"].unique()

array([2340, 2467.5, 675, 2312.5, 2435, 1787.5, 1135, 1210, 672.5, 990,
       'XXXXX', 302.5, 932.5, 295, 342.5, 1435, 1352.5, 2330, 430, 1617.5,
       1650, 2267.5, 1072.5, 1612.5, 650, 2117.5, 2202.5, 457.5, 965,
       2262.5, 2025, 745, 377.5, 722.5, 515, 2185, 272.5, 2197.5, 417.5,
       1920, 1905, 2297.5, 735, 2192.5, 162.5, 155, 1622.5, 1425, 290,
       1035, 2005, 2027.5, 822.5, 2070, 1790, 727.5, 660, 497.5, 1170,
       410, 927.5, 560, 1330, 707.5, 2002.5, 970, 2167.5, 1215, 967.5,
       1100, 1145, 1775, 452.5, 600, 2480, 495, 2382.5, 1630, 2157.5,
       267.5, 605, 765, 357.5, 952.5, 1472.5, 1697.5, 925, nan, 1027.5,
       1385, 2135, 1267.5, 472.5, 697.5, 2162.5, 1657.5, 2080, 355, 2225,
       1085, 1935, 1870, 1117.5, 1960, 172.5, 1422.5, 1002.5, 1305, 1075,
       2250, 335, 1535, 2495, 1510, 1172.5, 1055, 372.5, 2470, 1457.5,
       2040, 1227.5, 2322.5, 1985, 177.5, 142.5, 190, 2332.5, 1962.5,
       1970, 2100, 1542.5, 782.5, 2082.5, 655, 2390, 747.5, 1815, 215,
       315, 345, 2110, 1360, 1282.5, 1432.5, 127.5, 580, 720, 1750, 635,
       1290, 2152.5, 1520, 312.5, 1377.5, 1445, 2405, 2030, 815, 1647.5,
       1175, 1600, 2445, 1897.5, 1785, 1755, 2092.5, 480, 1792.5, 1350,
       2430, 1585, 1297.5, 705, 1222.5, 2150, 2412.5, 437.5, 1917.5, 1420,
       1342.5, 760, 1395, 1272.5, 382.5, 557.5, 987.5, 1285, 1582.5,
       647.5, 2187.5, 2102.5, 730, 137.5, 1307.5, 1690, 1575, 325, 587.5,
       1687.5, 210, 320, 1867.5, 132.5, 2142.5, 637.5, 687.5, 567.5,
       887.5, 1635, 850, 1345, 1177.5, 2047.5, 1607.5, 482.5, 737.5,
       2022.5, 1292.5, 1712.5, 2012.5, 292.5, 1702.5, 2247.5, 1092.5,
       1940, 1577.5, 135, 2417.5, 1500, 2310, 1930, 1225, 1080, 1200,
       1090, 1915, 185, 575, 680, 2277.5, 1277.5, 1392.5, 2017.5, 1967.5,
       1877.5, 1875, 1660, 1197.5, 777.5, 1782.5, 1335, 1152.5, 755, 1180,
       2437.5, 827.5, 447.5, 1165, 830, 1735, 167.5, 150, 1762.5, 2032.5,
       340, 2220, 420, 1557.5, 2327.5, 1977.5, 2372.5, 1530, 2205, 207.5,
       1742.5, 907.5, 1997.5, 2007.5, 1842.5, 1437.5, 227.5, 1857.5, 285,
       1380, 1127.5, 562.5, 2462.5, 1680, 2487.5, 2085, 622.5, 475,
       1802.5, 577.5, 2455, 130, 1097.5, 1020, 1317.5, 2497.5, 1270, 820,
       1880, 725, 915, 615, 200, 1242.5, 1230, 667.5, 2207.5, 1995, 762.5,
       845, 2400, 1560, 590, 1982.5, 1587.5, 2062.5, 1450, 1932.5, 1202.5,
       690, 1725, 657.5, 1235, 2272.5, 1237.5, 492.5, 842.5, 1417.5,
       1362.5, 1322.5, 882.5, 617.5, 1627.5, 550, 2125, 1050, 2355, 877.5,
       1555, 1190, 330, 2465, 775, 2397.5, 1942.5, 327.5, 2427.5, 1965,
       350, 1045, 982.5, 352.5, 1610, 1042.5, 1592.5, 555, 2425, 415, 445,
       1717.5, 862.5, 1467.5, 337.5, 632.5, 1475, 1132.5, 692.5, 242.5,
       465, 607.5, 1455, 1992.5, 397.5, 520, 1415, 2195, 682.5, 1065,
       1937.5, 1007.5, 2500, 985, 1502.5, 485, 2140, 885, 1120, 625,
       1247.5, 2477.5, 612.5, 287.5, 1845, 1257.5, 2422.5, 1707.5, 1262.5,
       125, 582.5, 2065, 2170, 902.5, 2280, 205, 2155, 920, 237.5, 1185,
       362.5, 1597.5, 1980, 857.5, 1122.5, 1032.5, 945, 1462.5, 2122.5,
       1652.5, 1907.5, 2010, 1602.5, 1922.5, 2365, 1860, 1067.5, 220, 510,
       2360, 522.5, 2020, 232.5, 852.5, 1525, 1912.5, 2282.5, 180, 370,
       1770, 1757.5, 1487.5, 1492.5, 1662.5, 1012.5, 250, 2452.5, 812.5,
       2067.5, 1187.5, 975, 1902.5, 2165, 537.5, 1130, 1015, 1300, 912.5,
       1010, 962.5, 1142.5, 955, 917.5, 152.5, 2212.5, 2335, 2317.5,
       1527.5, 670, 1157.5, 2325, 2490, 1675, 477.5, 527.5, 1850, 1645,
       1947.5, 260, 1402.5, 1730, 1062.5, 282.5, 652.5, 610, 1005, 1537.5,
       957.5, 487.5, 1667.5, 2217.5, 2285, 1037.5, 1337.5, 1250, 385, 855,
       1442.5, 2112.5, 1505, 1327.5, 592.5, 2147.5, 1852.5, 255, 192.5,
       1515, 2260, 1800, 2392.5, 1872.5, 2060, 427.5, 1470, 602.5, 405,
       817.5, 2415, 1655, 785, 247.5, 502.5, 1605, 1460, 2387.5, 1240,
       1245], dtype=object)

In [14]:
data.replace(to_replace=['XXXXX'],value=[0],inplace=True)

In [15]:
data.dtypes

Order ID                   object
Customer ID                object
Restuarant Name            object
Cookies Shipped            object
Revenue                   float64
Cost                      float64
profit                     object
Order Date         datetime64[ns]
Ship Date          datetime64[ns]
Order Status               object
Order Adress               object
dtype: object

In [16]:
data["Revenue"] - data["Cost"]

0      2340.0
1      2467.5
2       675.0
3      2312.5
4      2435.0
        ...
817     410.0
818     267.5
819    2260.0
820     155.0
821    1912.5
Length: 822, dtype: float64

In [17]:
data["profit"] = data["Revenue"] - data["Cost"]

In [18]:
data

,Order ID,Customer ID,Restuarant Name,Cookies Shipped,Revenue,Cost,profit,Order Date,Ship Date,Order Status,Order Adress
0,413383,152689,YT Restaurants,936,4680.0,2340.0,2340.0,2017-12-31,2018-01-05,Shipped,"136 Church St, New York City, NY 10001"
1,751142,985245,Quick Bite Convenience Stores,987,4935.0,2467.5,2467.5,2017-12-31,2018-01-04,Shipped,"562 2nd St, New York City, NY 10001"
2,876056,985245,Quick Bite Convenience Stores,270,1350.0,675.0,675.0,2017-12-30,2018-01-03,Shipped,"277 Main St, New York City, NY 10001"
3,548247,985245,Quick Bite Convenience Stores,925,4625.0,2312.5,2312.5,2017-12-30,2018-01-03,Shipped,"410 6th St, San Francisco, CA 94016"
4,626350,152689,YT Restaurants,974,4870.0,2435.0,2435.0,2017-12-29,2018-01-03,Shipped,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...,...,...,...,...,...
817,800525,785432,Park & Eat LLC,164,820.0,410.0,410.0,2017-01-03,2017-01-07,Shipped,"988 Spruce St, Boston, MA 02215"
818,311436,985245,Quick Bite Convenience Stores,107,535.0,267.5,267.5,2017-01-01,2017-01-05,Shipped,"969 11th St, Boston, MA 02215"
819,XXXXXX,XXXXXX,Promo,904,4520.0,2260.0,2260.0,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
820,617865,452584,Acme Grocery Stores,62,310.0,155.0,155.0,2017-01-01,2017-01-03,Shipped,"364 North St, Boston, MA 02215"
821,154036,325698,Cascade Grovers,765,3825.0,1912.5,1912.5,2017-01-01,2017-01-03,Shipped,"181 12th St, Austin, TX 73301"

In [19]:
import pandas as pd

In [20]:
a=pd.read_excel("2020 order data.xlsx")
b=pd.read_excel("2021 order data.xlsx")

In [21]:
a.columns

Index(['Order ID', 'Customer ID.1', 'Restaurant', 'Cookies Shipped', 'Revenue',
       'Cost', 'profit', 'Order Date', 'Ship Date', 'DateDifference',
       'Order Status'],
      dtype='object')

In [22]:
b.columns

Index(['Order ID', 'Customer ID.1', 'Restaurant', 'Cookies Shipped', 'Revenue',
       'Cost', 'profit', 'Order Date', 'Ship Date', 'DateDifference',
       'Order Status'],
      dtype='object')

In [23]:
#concatenating the two datas vertically and assigning it to a new variable
combined = pd.concat([a,b],axis =0)
combined

,Order ID,Customer ID.1,Restaurant,Cookies Shipped,Revenue,Cost,profit,Order Date,Ship Date,DateDifference,Order Status
0,413383,2480,YT Restaurants,936,4680,2340.0,2340.0,2020-12-31,2021-01-05,5,Shipped
1,751142,2891,Quick Bite Convenience Stores,987,4935,2467.5,2467.5,2020-12-31,2021-01-04,4,Shipped
2,876056,3170,Quick Bite Convenience Stores,270,1350,675.0,675.0,2020-12-30,2021-01-03,4,Shipped
3,548247,4084,Quick Bite Convenience Stores,925,4625,2312.5,2312.5,2020-12-30,2021-01-03,4,Shipped
4,626350,4535,YT Restaurants,974,4870,2435.0,2435.0,2020-12-29,2021-01-03,5,Shipped
...,...,...,...,...,...,...,...,...,...,...,...
80,558199,3480,Quick Bite Convenience Stores,606,24693,2268.0,22425.0,2021-11-27,2022-11-30,3,Shipped
81,681993,1839,YT Restaurants,243,55553,2542.0,53011.0,2021-11-25,2022-11-30,5,Shipped
82,214016,3184,Park & Eat LLC,416,33986,2671.0,31315.0,2021-11-25,2022-11-29,4,Shipped
83,773259,4979,Park & Eat LLC,666,46509,2923.0,43586.0,2021-11-24,2022-11-29,5,Shipped
84,994115,3229,YT Restaurants,234,52656,3518.0,49138.0,2021-11-24,2022-11-29,5,Shipped

In [24]:
combined.rename(columns={"Customer ID.1":"Customer ID"},inplace=True)
combined

,Order ID,Customer ID,Restaurant,Cookies Shipped,Revenue,Cost,profit,Order Date,Ship Date,DateDifference,Order Status
0,413383,2480,YT Restaurants,936,4680,2340.0,2340.0,2020-12-31,2021-01-05,5,Shipped
1,751142,2891,Quick Bite Convenience Stores,987,4935,2467.5,2467.5,2020-12-31,2021-01-04,4,Shipped
2,876056,3170,Quick Bite Convenience Stores,270,1350,675.0,675.0,2020-12-30,2021-01-03,4,Shipped
3,548247,4084,Quick Bite Convenience Stores,925,4625,2312.5,2312.5,2020-12-30,2021-01-03,4,Shipped
4,626350,4535,YT Restaurants,974,4870,2435.0,2435.0,2020-12-29,2021-01-03,5,Shipped
...,...,...,...,...,...,...,...,...,...,...,...
80,558199,3480,Quick Bite Convenience Stores,606,24693,2268.0,22425.0,2021-11-27,2022-11-30,3,Shipped
81,681993,1839,YT Restaurants,243,55553,2542.0,53011.0,2021-11-25,2022-11-30,5,Shipped
82,214016,3184,Park & Eat LLC,416,33986,2671.0,31315.0,2021-11-25,2022-11-29,4,Shipped
83,773259,4979,Park & Eat LLC,666,46509,2923.0,43586.0,2021-11-24,2022-11-29,5,Shipped
84,994115,3229,YT Restaurants,234,52656,3518.0,49138.0,2021-11-24,2022-11-29,5,Shipped

In [25]:
"""REPLACE YT RESTUARANT AS DELICIOUS FOOD,QUICK BITE CONVENIENCE STORE AS KFC
AND PARK & EAT LLC AS EXQUISITE FOODS"""

'REPLACE YT RESTUARANT AS DELICIOUS FOOD,QUICK BITE CONVENIENCE STORE AS KFC\nAND PARK & EAT LLC AS EXQUISITE FOODS'

In [26]:
combined["Restaurant"].replace(to_replace=["YT Restaurants","QUICK BITE CONVENIENCE STORE"," PARK & EAT LLC"],
                               value=[" DELICIOUS FOOD","KFC","EXQUISITE"],inplace=True)

In [27]:
combined

,Order ID,Customer ID,Restaurant,Cookies Shipped,Revenue,Cost,profit,Order Date,Ship Date,DateDifference,Order Status
0,413383,2480,DELICIOUS FOOD,936,4680,2340.0,2340.0,2020-12-31,2021-01-05,5,Shipped
1,751142,2891,Quick Bite Convenience Stores,987,4935,2467.5,2467.5,2020-12-31,2021-01-04,4,Shipped
2,876056,3170,Quick Bite Convenience Stores,270,1350,675.0,675.0,2020-12-30,2021-01-03,4,Shipped
3,548247,4084,Quick Bite Convenience Stores,925,4625,2312.5,2312.5,2020-12-30,2021-01-03,4,Shipped
4,626350,4535,DELICIOUS FOOD,974,4870,2435.0,2435.0,2020-12-29,2021-01-03,5,Shipped
...,...,...,...,...,...,...,...,...,...,...,...
80,558199,3480,Quick Bite Convenience Stores,606,24693,2268.0,22425.0,2021-11-27,2022-11-30,3,Shipped
81,681993,1839,DELICIOUS FOOD,243,55553,2542.0,53011.0,2021-11-25,2022-11-30,5,Shipped
82,214016,3184,Park & Eat LLC,416,33986,2671.0,31315.0,2021-11-25,2022-11-29,4,Shipped
83,773259,4979,Park & Eat LLC,666,46509,2923.0,43586.0,2021-11-24,2022-11-29,5,Shipped
84,994115,3229,DELICIOUS FOOD,234,52656,3518.0,49138.0,2021-11-24,2022-11-29,5,Shipped

In [28]:
#exporting the final result back to excel
combined.to_excel("combined excel.xlsx")